"""0001

Revision ID: 193c33e2fcee
Revises: None
Create Date: 2015-09-04 23:33:46.146180

"""

# revision identifiers, used by Alembic.
revision = '193c33e2fcee'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('brewer', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('style', sa.String(length=10), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('brewed', sa.DateTime(), nullable=True),
    sa.Column('bottled', sa.DateTime(), nullable=True),
    sa.Column('og', sa.Float(), nullable=True),
    sa.Column('fg', sa.Float(), nullable=True),
    sa.Column('fermentables', sa.Text(), nullable=True),
    sa.Column('mash_schedule', sa.Text(), nullable=True),
    sa.Column('hops', sa.Text(), nullable=True),
    sa.Column('yeast', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('brew_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('aroma_score', sa.Integer(), nullable=False),
    sa.Column('aroma_comments', sa.Text(), nullable=True),
    sa.Column('appearance_score', sa.Integer(), nullable=False),
    sa.Column('appearance_comments', sa.Text(), nullable=True),
    sa.Column('flavor_score', sa.Integer(), nullable=False),
    sa.Column('flavor_comments', sa.Text(), nullable=True),
    sa.Column('mouthfeel_score', sa.Integer(), nullable=False),
    sa.Column('mouthfeel_comments', sa.Text(), nullable=True),
    sa.Column('impression_score', sa.Integer(), nullable=False),
    sa.Column('impression_comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brew_id'], [u'brew.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('brew')
    ### end Alembic commands ###
